version: "3.8"
services:
  db:
    image: mongo:7.0.0-rc8-jammy
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3900:3900"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
volumes:
  db:
